## 38. 프로젝트 루트 확인

In [167]:
from pathlib import Path

project_root = Path.cwd() # 현재 경로 저장(현재 작업하는 것은 어디에 있나요) csv 파일 가져오기 위해
print("프로젝트 루트:", project_root)
if project_root.name == "notebooks":
    project_root = project_root.parent # 상위 경로

# 일반적으로 파이썬에서 /는 나눗셈 연산자이지만, Path 객체끼리 혹은 Path 객체와 문자열 사이에 /를 쓰면 "경로(Path)를 이어 붙여라"는 의미로 동작하도록 재정의되어 있습니다.
data_dir = project_root / "data" / "raw"


print("프로젝트 루트:", project_root)
print("데이터 폴더:", data_dir)
print("데이터 폴더 존재:", data_dir.exists()) # data_dir이 존재하는가

프로젝트 루트: /Users/chaehuiju/dev/ai-data-analysis/notebooks
프로젝트 루트: /Users/chaehuiju/dev/ai-data-analysis
데이터 폴더: /Users/chaehuiju/dev/ai-data-analysis/data/raw
데이터 폴더 존재: True

## 39. 필수 파일 확인

In [168]:
required_files = [
    "customers.csv",
    "products.csv",
    "orders.csv",
    "order_items.csv",
]

for file_name in required_files: # 파일 개수만큼 for문 돌 것 (여기선 4개)
    file_path = data_dir / file_name # /로 경로 이어붙이기
    
    # 파일이름, 파일경로 존재여부, 파일이 존재할 때 파일 사이즈(존재하지 않으면 0) -> 리스트 컴프리핸션 
    print(file_name, file_path.exists(), file_path.stat().st_size if file_path.exists() else 0)

customers.csv True 5490
products.csv True 4002
orders.csv True 11392
order_items.csv True 14608

# Part 10. 4개 CSV 불러오기와 크기 요약
## 40. 데이터 불러오기

In [169]:
import pandas as pd

# pd(판다스).read_csv(파일경로(여기서도 파일이름 /로 이어붙이기))  -> 네 변수는 파이썬이 이해할 수 있는 매개변수 : df(데이터프레임)
customers = pd.read_csv(data_dir / "customers.csv") # 고객정보
products = pd.read_csv(data_dir / "products.csv") # 제품 정보
orders = pd.read_csv(data_dir / "orders.csv") # 주문 정보(영수증)
order_items = pd.read_csv(data_dir / "order_items.csv") # 세부 주문 내역

## 41. DataFrame 사전 만들기

In [170]:

# 키-값 dictionary 만들기
datasets = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "order_items": order_items,
}

print(datasets)

{'customers':      customer_id name gender  age city signup_date
0              1  김수민      F   19   광주  2024-04-09
1              2  장춘자      F   32   대구  2023-11-12
2              3  김상현      F   61   성남  2025-02-12
3              4  김재호      F   55   울산  2025-03-28
4              5  최준서      F   19   부산  2023-08-16
..           ...  ...    ...  ...  ...         ...
145          146  고준영      M   61   성남  2023-11-11
146          147  김예은      M   19   부산  2025-06-07
147          148  김준혁      M   29   고양  2024-02-24
148          149  안성현      M   20   부산  2026-03-30
149          150  이경숙      M   40   대전  2026-06-13

[150 rows x 6 columns], 'products':     product_id product_name category   price
0            1  전자기기 상품 001     전자기기  160000
1            2    도서 상품 002       도서   34000
2            3  전자기기 상품 003     전자기기  152000
3            4  생활용품 상품 004     생활용품   70000
4            5    식품 상품 005       식품  186000
..         ...          ...      ...     ...
95          96  생활용품 상품 096     생활용품  112000
96          97  전자기기 상품 097     전자기기  154000
97          98   스포츠 상품 098      스포츠   10000
98          99    뷰티 상품 099       뷰티  200000
99         100    도서 상품 100       도서  102000

[100 rows x 4 columns], 'orders':      order_id  customer_id  order_date payment_method order_status
0           1          123  2025-09-08           card    completed
1           2           77  2026-04-28      naver_pay    cancelled
2           3          138  2026-02-02  bank_transfer    cancelled
3           4           57  2026-05-12      kakao_pay    cancelled
4           5          125  2026-04-17           card    cancelled
..        ...          ...         ...            ...          ...
296       297           22  2026-01-31  bank_transfer    completed
297       298           64  2025-11-02      naver_pay    cancelled
298       299          135  2026-03-05  bank_transfer    completed
299       300           96  2026-03-06      kakao_pay    cancelled
300       301          300  2026-03-06      kakao_pay    cancelled

[301 rows x 5 columns], 'order_items':      order_item_id  order_id  product_id  quantity  unit_price
0                1         1         100         3      102000
1                2         1          87         5       25000
2                3         1           7         3      142000
3                4         1           9         3      193000
4                5         2          72         4      189000
..             ...       ...         ...       ...         ...
761            762       299           8         2      189000
762            763       299          12         4      175000
763            764       300          59         5       32000
764            765       400          59         5       32000
765            766       301         200         5       32000

[766 rows x 5 columns]}

## 42. 크기 요약

In [171]:
'''
pandas.DataFrame()은 파이썬 데이터 분석 라이브러리인 Pandas에서 '표(Table) 형태의 데이터 구조'를 만들어내는 클래스(함수)입니다.
엑셀의 시트(Sheet)나 SQL의 테이블처럼 행(Row)과 열(Column)로 이루어진 2차원 데이터 구조를 생성하는 기능을 합니다.

data (핵심 매개변수):
표에 들어갈 실제 데이터를 받습니다.
리스트, 딕셔너리, NumPy 배열 등 다양한 자료형을 전달할 수 있습니다.

columns (선택 매개변수):
각 열(Column)의 이름을 직접 지정할 때 사용합니다.
데이터가 딕셔너리 형태일 경우, 키(Key) 값이 자동으로 열 이름으로 채워집니다.

index (선택 매개변수):
각 행(Row)의 이름(인덱스)을 지정합니다. 기본값은 0, 1, 2... 형태의 정수입니다.
'''
shape_summary = pd.DataFrame(
    [
        # for문 리스트 컴프리핸션 {만들고 싶은 결과} for ~~
        {
            "dataset": name,
            #df.shape는 데이터프레임의 크기를 (행 개수, 열 개수) 형태의 튜플(Tuple)로 반환
            "rows": df.shape[0], #df.shape[0]: 인덱스 0번에 위치한 행(Row)의 개수
            "columns": df.shape[1], # df.shape[1]: 인덱스 1번에 위치한 열(Column)의 개수
            
        }
        
        for name, df in datasets.items()
    ]
)

print(shape_summary) #notebook에서는 shape_summary만써도 출력이 되지만 py파일에서는 안되므로 가급적 print문 사용하기

       dataset  rows  columns
0    customers   150        6
1     products   100        4
2       orders   301        5
3  order_items   766        5

## 43. 한 행의 의미 기록

### 데이터셋별 한 행의 의미

- customers: 고객 한 명
- products: 상품 한 개
- orders: 주문 한 건
- order_items: 주문에 포함된 상품 한 항목

rows에서 의미하는 것 개수, columns에서 의미하는 것 특성 개수

## 44. 처음과 마지막 행 확인

In [172]:
# (모든 데이터를 살필 수 없으니 어떤 데이터가 있는지 맛보는 것, 어떤 데이터가 있는지 감잡기) 

for name, df in datasets.items(): # datasets는 4개
    print(f"\n[{name}] 앞부분")
    display(df.head()) # 앞부분의 괄호안을 비우면 5개, 숫자를 쓰면 그 만큼의 데이터.
    # print(df.head())로 해도 되는데 jupyter랑 colab에서 눈으로 데이터를 편하게 확인하기 위해..
    print(f"[{name}] 뒷부분")
    display(df.tail()) # 뒷부분의 5개
    

'''
    확인 내용:
    
    • 한글이 정상 표시되는가?
    • 날짜 값은 어떤 형식인가?
    • 숫자 값에 쉼표나 문자가 있는가?
    • 마지막 행에 합계나 설명 행이 있는가?
    • 한 행의 의미가 예상과 일치하는가?
'''

[customers] 앞부분

   customer_id name gender  age city signup_date
0            1  김수민      F   19   광주  2024-04-09
1            2  장춘자      F   32   대구  2023-11-12
2            3  김상현      F   61   성남  2025-02-12
3            4  김재호      F   55   울산  2025-03-28
4            5  최준서      F   19   부산  2023-08-16

[customers] 뒷부분

     customer_id name gender  age city signup_date
145          146  고준영      M   61   성남  2023-11-11
146          147  김예은      M   19   부산  2025-06-07
147          148  김준혁      M   29   고양  2024-02-24
148          149  안성현      M   20   부산  2026-03-30
149          150  이경숙      M   40   대전  2026-06-13

[products] 앞부분

   product_id product_name category   price
0           1  전자기기 상품 001     전자기기  160000
1           2    도서 상품 002       도서   34000
2           3  전자기기 상품 003     전자기기  152000
3           4  생활용품 상품 004     생활용품   70000
4           5    식품 상품 005       식품  186000

[products] 뒷부분

    product_id product_name category   price
95          96  생활용품 상품 096     생활용품  112000
96          97  전자기기 상품 097     전자기기  154000
97          98   스포츠 상품 098      스포츠   10000
98          99    뷰티 상품 099       뷰티  200000
99         100    도서 상품 100       도서  102000

[orders] 앞부분

   order_id  customer_id  order_date payment_method order_status
0         1          123  2025-09-08           card    completed
1         2           77  2026-04-28      naver_pay    cancelled
2         3          138  2026-02-02  bank_transfer    cancelled
3         4           57  2026-05-12      kakao_pay    cancelled
4         5          125  2026-04-17           card    cancelled

[orders] 뒷부분

     order_id  customer_id  order_date payment_method order_status
296       297           22  2026-01-31  bank_transfer    completed
297       298           64  2025-11-02      naver_pay    cancelled
298       299          135  2026-03-05  bank_transfer    completed
299       300           96  2026-03-06      kakao_pay    cancelled
300       301          300  2026-03-06      kakao_pay    cancelled

[order_items] 앞부분

   order_item_id  order_id  product_id  quantity  unit_price
0              1         1         100         3      102000
1              2         1          87         5       25000
2              3         1           7         3      142000
3              4         1           9         3      193000
4              5         2          72         4      189000

[order_items] 뒷부분

     order_item_id  order_id  product_id  quantity  unit_price
761            762       299           8         2      189000
762            763       299          12         4      175000
763            764       300          59         5       32000
764            765       400          59         5       32000
765            766       301         200         5       32000

'\n    확인 내용:\n\n    • 한글이 정상 표시되는가?\n    • 날짜 값은 어떤 형식인가?\n    • 숫자 값에 쉼표나 문자가 있는가?\n    • 마지막 행에 합계나 설명 행이 있는가?\n    • 한 행의 의미가 예상과 일치하는가?\n'

## 45. 컬럼명 확인

In [173]:
for name, df in datasets.items():
    print(name, df.columns.tolist()) #ㅍ행이름은 df.index.tolist() 이다. 인덱스로 지칭! 헷갈리지 않을 것!

customers ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
products ['product_id', 'product_name', 'category', 'price']
orders ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']
order_items ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

## 46. 컬럼명 공백 점검

In [174]:
# 컬럼명에 공백이 있으면 안됨, 외부데이터들은 폼이 일정하지 않을 가능성이 커서 점검 필요

for name, df in datasets.items():
    suspicious = [
        col for col in df.columns
        if col != col.strip() # col.strip()는 컬럼명의 앞이나 뒷 공백을 모두 제거
    ]
    print(name, suspicious)
    
# 공백이 없으면 suspicious 리스트에 들어갈 컬럼명이 없으므로 []라고 결과 나옴.

customers []
products []
orders []
order_items []

## 47. info() 실행

1. 데이터의 전체적인 윤곽을 빠르게 파악할 때

    전체 행(Row) 수가 몇 개인지
    컬럼(Column)이 총 몇 개인지
    각 컬럼의 이름이 정확히 무엇인지 한눈에 확인하고 싶을 때 사용합니다.

2. 결측치(누락된 값) 유무를 확인할 때

    Non-Null Count(Null이 아닌 값의 개수)를 보여주기 때문에, 전체 행 수와 비교해서 어느 컬럼에 값이 비어있는지(NaN) 빠르게 발견할 수 있습니다.

3. 데이터 타입(dtype)을 점검할 때

    숫자로 들어가 있어야 할 값이 문자열(object)로 읽히지 않았는지, 날짜 데이터가 문자열로 남아있지 않은지 등 전처리 전 데이터 타입의 정합성을 확인할 때 필수적입니다.

4. 메모리 사용량을 확인할 때

    데이터셋의 용량이 얼마나 큰지(memory usage) 확인하여 메모리 과부하를 예방할 때 사용합니다.

In [175]:
for name, df in datasets.items():
    print(f"\n===== {name} =====")
    df.info()
    
# non-null: 결측값이 없다 (값이 없는 게 없다)
# signup_date가 str이므로 나중에 데이터 타입을 바꿀 필요가 있음

===== customers =====
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  150 non-null    int64
 1   name         150 non-null    str
 2   gender       150 non-null    str
 3   age          150 non-null    int64
 4   city         150 non-null    str
 5   signup_date  150 non-null    str
dtypes: int64(2), str(4)
memory usage: 7.2 KB

===== products =====
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    int64
 1   product_name  100 non-null    str
 2   category      100 non-null    str
 3   price         100 non-null    int64
dtypes: int64(2), str(2)
memory usage: 3.3 KB

===== orders =====
<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        301 non-null    int64
 1   customer_id     301 non-null    int64
 2   order_date      301 non-null    str
 3   payment_method  301 non-null    str
 4   order_status    301 non-null    str
dtypes: int64(2), str(3)
memory usage: 11.9 KB

===== order_items =====
<class 'pandas.DataFrame'>
RangeIndex: 766 entries, 0 to 765
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  766 non-null    int64
 1   order_id       766 non-null    int64
 2   product_id     766 non-null    int64
 3   quantity       766 non-null    int64
 4   unit_price     766 non-null    int64
dtypes: int64(5)
memory usage: 30.1 KB

## 48. dtype 요약표

In [176]:

dtype_rows = [] # dtype_rows를 가져올 수 있는 빈 리스트 변수 선언

for name, df in datasets.items(): # 4번 돌 것
    # 데이터 타입 수만큼 for문 돌 것(각 데이터프레임마다 다름)
    for column, dtype in df.dtypes.items(): # dtypes는 series객체 형태다. items()를 쓰지 않으면 컬럼명은 안나오고 데이터타입만 나옴 items는 쌍으로 뽑아내기 위함
        
        dtype_rows.append(
            {
                "dataset": name,
                "column": column,
                "dtype": str(dtype), #dtype은 파이썬 기본 문자열(str)이 아니라 NumPy나 Pandas의 전용 타입 객체(Object)이기 때문에 str()
            
            #딕셔너리 리스트 dtype_rows의 최종 형태 예시
            #{"dataset": "customers", "column": "age", "dtype": "int64"},
            #{"dataset": "customers", "column": "name", "dtype": "object"}
            #이런 형태의 데이터 구조는 나중에 pd.DataFrame(dtype_rows)로 변환하여 깔끔한 표(데이터프레임)로 새로 만들 때 자주 사용
            
            }
        )

dtype_summary = pd.DataFrame(dtype_rows)
print(dtype_summary)
# customers의 signup_date와 orders의 order_date는 날짜 형태임에도 str이므로 변환이 필요함을 알 수 있다.

        dataset          column  dtype
0     customers     customer_id  int64
1     customers            name    str
2     customers          gender    str
3     customers             age  int64
4     customers            city    str
5     customers     signup_date    str
6      products      product_id  int64
7      products    product_name    str
8      products        category    str
9      products           price  int64
10       orders        order_id  int64
11       orders     customer_id  int64
12       orders      order_date    str
13       orders  payment_method    str
14       orders    order_status    str
15  order_items   order_item_id  int64
16  order_items        order_id  int64
17  order_items      product_id  int64
18  order_items        quantity  int64
19  order_items      unit_price  int64

## 49. 날짜형 후보 확인

In [177]:
date_columns = {
    # 날짜 프레임이 들어있던 것들
    "customers": ["signup_date"], # 이 예제에서는 아니지만, 혹시 여러 개 일수 있으니 리스트로.
    "orders": ["order_date"],
}
# str형식을 날짜 형식으로 바꾸어야 함
for dataset_name, columns in date_columns.items():
    df = datasets[dataset_name]
    for column in columns:
        converted = pd.to_datetime( # 날짜 형식으로 바꾸는 메소드
            df[column],
            errors="coerce"

            # errors="coerce"
            # 날짜로 바꾸기 힘든 이상한 값(예: "2024-13-45", "알수없음", "-" 등)을 만나면 오류를 무시하고
            # NaT (Null/결측치)로 채웁니다.
            # 데이터 전처리 과정에서 어떤 행에 이상한 날짜 데이터가 섞여 있는지 찾아낼 때 핵심적으로 사용됩니다.
            # errors="raise" (기본값)
            # 날짜 변환이 불가능한 값이 하나라도 있으면 즉시 ValueError 에러를 발생시키고 전체 코드가 중단됩니다.
            # errors="ignore"
            # 변환할 수 없는 값을 만나면 에러를 내는 대신 변환하지 않고 원래 값(문자열 그대로)을 유지합니다.

        )

        print(
            dataset_name,
            column,
            "원본 dtype:", df[column].dtype,
            "변환 실패:", converted.isna().sum() # 결측치 세기 (null이 True면 1)
        )

customers signup_date 원본 dtype: str 변환 실패: 0
orders order_date 원본 dtype: str 변환 실패: 0

## 50. 결측치 개수

In [178]:
for name, df in datasets.items():
    print(F"\n[{name}]")
    display(df.isna().sum().to_frame("missing_count")) # to_frame은 데이터프레임으로 만드는 것(인자는 열 이름이 됨)

[customers]

             missing_count
customer_id              0
name                     0
gender                   0
age                      0
city                     0
signup_date              0

[products]

              missing_count
product_id                0
product_name              0
category                  0
price                     0

[orders]

                missing_count
order_id                    0
customer_id                 0
order_date                  0
payment_method              0
order_status                0

[order_items]

               missing_count
order_item_id              0
order_id                   0
product_id                 0
quantity                   0
unit_price                 0

## 51. 결측치 비율

In [179]:
missing_summaries = []

for name, df in datasets.items():
    summary = pd.DataFrame(
        {
            "missing_count": df.isna().sum(),
            "missing_rate_pct": (
                df.isna().mean() * 100
            ).round(2),
        }
    )
    summary.insert(0, "dataset", name)
    summary.insert(1, "column", summary.index)
    missing_summaries.append(summary.reset_index(drop=True))
missing_summary = pd.concat(
    missing_summaries,
    ignore_index=True
)

print(missing_summary)

        dataset          column  missing_count  missing_rate_pct
0     customers     customer_id              0               0.0
1     customers            name              0               0.0
2     customers          gender              0               0.0
3     customers             age              0               0.0
4     customers            city              0               0.0
5     customers     signup_date              0               0.0
6      products      product_id              0               0.0
7      products    product_name              0               0.0
8      products        category              0               0.0
9      products           price              0               0.0
10       orders        order_id              0               0.0
11       orders     customer_id              0               0.0
12       orders      order_date              0               0.0
13       orders  payment_method              0               0.0
14       orders    order_status              0               0.0
15  order_items   order_item_id              0               0.0
16  order_items        order_id              0               0.0
17  order_items      product_id              0               0.0
18  order_items        quantity              0               0.0
19  order_items      unit_price              0               0.0

## 52. 전체 행 중복

In [180]:
for name, df in datasets.items():
    print(name, "전체 중복:", df.duplicated().sum())

customers 전체 중복: 0
products 전체 중복: 0
orders 전체 중복: 0
order_items 전체 중복: 0

## 53. 주요 ID 점검

In [181]:
primary_keys = {
    "customers": "customer_id",
    "products": "product_id",
    "orders": "order_id",
    "order_items": "order_item_id",
}

id_check_rows = []

for name, key in primary_keys.items():
    df = datasets[name]
    id_check_rows.append(
        {
            "dataset": name,
            "key": key,
            "missing": df[key].isna().sum(),
            #프라이머리 키는 unique해야하고 null일 수 없고 duplicated할 수 없다.
            "duplicates": df[key].duplicated().sum(),
            "unique": df[key].nunique(),
            "rows": len(df),
        }
    )

id_check_summary = pd.DataFrame(id_check_rows)

print(id_check_summary)

       dataset            key  missing  duplicates  unique  rows
0    customers    customer_id        0           0     150   150
1     products     product_id        0           0     100   100
2       orders       order_id        0           0     301   301
3  order_items  order_item_id        0           0     766   766

## 54. 발견 내용을 기록합니다.


### 데이터 품질 발견 기록
| 데이터셋        | 컬럼            | 문제 종류       |         건수 | 해석                          | 처리 여부           |
| ----------- | ------------- | ----------- | ---------: | --------------------------- | --------------- |
| customers   | signup_date   | 날짜 변환 실패 | 0 | 가입일자 이상 없음 | N/A |
| orders      | order_date    | 날짜 변환 실패 | 0 | 주문일자 이상 없음 | N/A |
| customers   | (해당 컬럼)       | 결측치         |      0 | 결측 없음                   | N/A |
| products    | (해당 컬럼)       | 결측치         |      0 | 결측 없음                   | N/A |
| orders      | (해당 컬럼)       | 결측치         |      0 | 결측 없음                   | N/A |
| order_items | (해당 컬럼)       | 결측치         |      0  | 결측 없음                   | N/A |
| (해당 데이터셋)   | (Primary Key) | ID 중복       |      0  | 중복 없음               | N/A |
| (해당 데이터셋)   | (Primary Key) | ID 결측       |      0  | 결측 없음        | N/A |

## 55. 숫자형 기본 통계

In [182]:

#info()메소드는 전체 컬럼, null 개수 확인 등등, describe()메소드는 숫자형 컬럼들에 대한 통계값을 확인할 수 있음
print(customers[["age"]].describe())

print(products[["price"]].describe())

print(order_items[["quantity", "unit_price"]].describe())

              age
count  150.000000
mean    42.086667
std     15.613166
min     19.000000
25%     29.000000
50%     40.000000
75%     57.000000
max     69.000000
               price
count     100.000000
mean   110040.000000
std     56433.910574
min      5000.000000
25%     65750.000000
50%    112000.000000
75%    161000.000000
max    200000.000000
         quantity     unit_price
count  766.000000     766.000000
mean     3.058747  108361.618799
std      1.412529   57056.316997
min      1.000000    5000.000000
25%      2.000000   62000.000000
50%      3.000000  111000.000000
75%      4.000000  161000.000000
max      5.000000  200000.000000

## 56. 범주형 값 확인

In [183]:
category_columns = {
    "customers": ["gender", "city"],
    "products": ["category"],
    "orders": ["payment_method", "order_status"],
}

for dataset_name, columns in category_columns.items():
    df = datasets[dataset_name]
    for column in columns:
        print(f"\n[{dataset_name}.{column}]")
        display(
            df[column]
            .value_counts(dropna=False)
            .to_frame("count")
        )

[customers.gender]

        count
gender
F          84
M          66

[customers.city]

      count
city
성남       21
광주       17
부산       16
대구       15
서울       15
울산       14
인천       14
대전       14
수원       13
고양       11

[products.category]

          count
category
스포츠          19
전자기기         17
생활용품         16
뷰티           16
도서           14
패션           11
식품            7

[orders.payment_method]

                count
payment_method
kakao_pay          80
naver_pay          77
bank_transfer      74
card               70

[orders.order_status]

              count
order_status
completed       184
cancelled        65
refunded         52

## 57. 날짜 범위 확인

In [184]:
signup_dates = pd.to_datetime(
    customers["signup_date"],
    errors="coerce"
)

order_dates = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

print("가입일 변환 실패:", signup_dates.isna().sum())
print("가입일 범위:", signup_dates.min(), "~", signup_dates.max())
print("주문일 변환 실패:", order_dates.isna().sum())
print("주문일 범위:", order_dates.min(), "~", order_dates.max())

가입일 변환 실패: 0
가입일 범위: 2023-08-15 00:00:00 ~ 2026-08-04 00:00:00
주문일 변환 실패: 0
주문일 범위: 2025-08-08 00:00:00 ~ 2026-08-08 00:00:00

## 58. 날짜 관계 점검 준비

주문일과 고객 가입일을 직접 비교하려면 두 데이터를 연결해야 합니다.

## 59. 참조하지 못한 고객 ID

In [185]:
unknown_customer_ids = sorted(
    # 주문서에 있는 주문한 고객의 ID (1,2,3 ...) :child
    set(orders["customer_id"].dropna())
    # 구체적인 주문한 고객의 정보가 있는 곳은 customers. 아이디로 조회. : parent
    - set(customers["customer_id"].dropna()) )
    # 한명의 고객이 여러개의 주문을 할 수 있으므로.

print("존재하지 않는 customer_id:", unknown_customer_ids)

존재하지 않는 customer_id: [300]

## 60. 참조하지 못한 주문 ID

In [186]:
unknown_order_ids = sorted(
    
    set(order_items["order_id"].dropna()) # child
    - set(orders["order_id"].dropna()) # parent
    # 하나의 주문은 여러개의 오더아이템을 가질 수 있다. 오더아이템은 반드시 오더아이디가 있어야한다.
)

print("존재하지 않는 order_id:", unknown_order_ids)

존재하지 않는 order_id: [400]

## 61. 참조하지 못한 상품 ID

In [187]:
unknown_product_ids = sorted(
    set(order_items["product_id"].dropna())
    - set(products["product_id"].dropna())
)

print("존재하지 않는 product_id:", unknown_product_ids)

존재하지 않는 product_id: [200]

## 62. 반복 점검 함수

In [188]:
# 반복 점검 함수 정의
def inspect_dataframe(
    name: str,
    df: pd.DataFrame,
    primary_key: str | None = None,
) -> dict:
    
    result = {
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "column_names": df.columns.tolist(),
        "dtypes": {
            column: str(dtype)
            for column, dtype in df.dtypes.items()
        },
        "missing_total": int(df.isna().sum().sum()),
        "duplicate_rows": int(df.duplicated().sum()),
    }

    if primary_key is not None:
        result["primary_key"] = primary_key
        result["key_missing"] = int(
            df[primary_key].isna().sum()
        )
        result["key_duplicates"] = int(
            df[primary_key].duplicated().sum()
        )
        result["key_unique"] = int(
            df[primary_key].nunique()
        )

    return result

In [189]:
# 반복 점검 함수 호출
inspection_results = []

for name, df in datasets.items():
    inspection_results.append(
        inspect_dataframe(
            name,
            df,
            primary_keys[name],
        )
    )

inspection_results

[{'dataset': 'customers',
  'rows': 150,
  'columns': 6,
  'column_names': ['customer_id',
   'name',
   'gender',
   'age',
   'city',
   'signup_date'],
  'dtypes': {'customer_id': 'int64',
   'name': 'str',
   'gender': 'str',
   'age': 'int64',
   'city': 'str',
   'signup_date': 'str'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'customer_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 150},
 {'dataset': 'products',
  'rows': 100,
  'columns': 4,
  'column_names': ['product_id', 'product_name', 'category', 'price'],
  'dtypes': {'product_id': 'int64',
   'product_name': 'str',
   'category': 'str',
   'price': 'int64'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'product_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 100},
 {'dataset': 'orders',
  'rows': 301,
  'columns': 5,
  'column_names': ['order_id',
   'customer_id',
   'order_date',
   'payment_method',
   'order_status'],
  'dtypes': {'order_id': 'int64',
   'customer_id': 'int64',
   'order_date': 'str',
   'payment_method': 'str',
   'order_status': 'str'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'order_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 301},
 {'dataset': 'order_items',
  'rows': 766,
  'columns': 5,
  'column_names': ['order_item_id',
   'order_id',
   'product_id',
   'quantity',
   'unit_price'],
  'dtypes': {'order_item_id': 'int64',
   'order_id': 'int64',
   'product_id': 'int64',
   'quantity': 'int64',
   'unit_price': 'int64'},
  'missing_total': 0,
  'duplicate_rows': 0,
  'primary_key': 'order_item_id',
  'key_missing': 0,
  'key_duplicates': 0,
  'key_unique': 766}]

## 63. LLM에 전달할 안전한 구조 요약

In [190]:
safe_schema_summary = {
    "datasets": inspection_results,
    "relationships": {
        "orders.customer_id": {
            "references": "customers.customer_id",
            "unknown_count": len(unknown_customer_ids),
        },

        "order_items.order_id": {
            "references": "orders.order_id",
            "unknown_count": len(unknown_order_ids),
        },

        "order_items.product_id": {
            "references": "products.product_id",
            "unknown_count": len(unknown_product_ids),
        },
    },
}

safe_schema_summary

{'datasets': [{'dataset': 'customers',
   'rows': 150,
   'columns': 6,
   'column_names': ['customer_id',
    'name',
    'gender',
    'age',
    'city',
    'signup_date'],
   'dtypes': {'customer_id': 'int64',
    'name': 'str',
    'gender': 'str',
    'age': 'int64',
    'city': 'str',
    'signup_date': 'str'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'customer_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 150},
  {'dataset': 'products',
   'rows': 100,
   'columns': 4,
   'column_names': ['product_id', 'product_name', 'category', 'price'],
   'dtypes': {'product_id': 'int64',
    'product_name': 'str',
    'category': 'str',
    'price': 'int64'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'product_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 100},
  {'dataset': 'orders',
   'rows': 301,
   'columns': 5,
   'column_names': ['order_id',
    'customer_id',
    'order_date',
    'payment_method',
    'order_status'],
   'dtypes': {'order_id': 'int64',
    'customer_id': 'int64',
    'order_date': 'str',
    'payment_method': 'str',
    'order_status': 'str'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'order_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 301},
  {'dataset': 'order_items',
   'rows': 766,
   'columns': 5,
   'column_names': ['order_item_id',
    'order_id',
    'product_id',
    'quantity',
    'unit_price'],
   'dtypes': {'order_item_id': 'int64',
    'order_id': 'int64',
    'product_id': 'int64',
    'quantity': 'int64',
    'unit_price': 'int64'},
   'missing_total': 0,
   'duplicate_rows': 0,
   'primary_key': 'order_item_id',
   'key_missing': 0,
   'key_duplicates': 0,
   'key_unique': 766}],
 'relationships': {'orders.customer_id': {'references': 'customers.customer_id',
   'unknown_count': 1},
  'order_items.order_id': {'references': 'orders.order_id',
   'unknown_count': 1},
  'order_items.product_id': {'references': 'products.product_id',
   'unknown_count': 1}}}

## 64. LLM 구조 점검 프롬프트


나는 온라인 쇼핑몰 데이터 분석을 준비하고 있습니다.
아래 정보는 원본 행이 아니라 구조 점검 요약입니다.

[여기에 safe_schema_summary의 내용을 붙여 넣기]

다음을 검토해 주세요.

1. 각 데이터셋에서 한 행이 무엇을 의미할 가능성이 높은지 설명해 주세요.
2. 주요 ID와 외래 키를 구분해 주세요.
3. 즉시 삭제하면 안 되는 결측치·중복 사례를 알려 주세요.
4. 추가로 점검할 구조 문제를 우선순위대로 제안해 주세요.
5. 실제 데이터에 없는 컬럼이나 관계를 가정하지 마세요.
6. 각 제안에 대해 확인할 pandas 코드의 목적만 설명해 주세요.

개인정보나 원본 고객 행은 제공하지 않았습니다.

## 65. LLM 답변 검증표

| 검증 항목 | 확인 내용 |
|---|---|
| 컬럼 존재 | 실제 컬럼명과 일치하는가? |
|한 행의 의미 | 데이터셋 역할과 일치하는가?|
|ID 해석 | 식별자를 수치 변수로 해석하지 않았는가?|
|중복 해석 | 반복 가능한 외래 키를 오류로 판단하지 않았는가?|
|결측 해석 | 업무 의미 확인 없이 삭제를 권하지 않는가?|
|관계 | 실제 연결 키와 일치하는가?|
|개인정보 | 추가 원본 행 제공을 요구하지 않는가?|

## 66. 데이터 첫인상 보고서



### 1. 데이터 파일

| 데이터셋 | 한 행의 의미 | 행 | 열 | 주요 ID |

|---|---|---:|---:|---|

| customers | | | | |

| products | | | | |

| orders | | | | |

| order_items | | | | |


### 2. 컬럼과 타입
### 3. 결측치
### 4. 전체 중복
### 5. 주요 ID 결측·중복
### 6. 숫자형 범위
### 7. 범주형 값
### 8. 날짜 범위와 변환 실패
### 9. 파일 간 참조 무결성
### 10. 발견한 문제
### 11. 즉시 처리하지 않은 이유
### 12. 다음 전처리 단계에서 결정할 내용

67. FileNotFoundError

In [191]:
from pathlib import Path

print(Path.cwd())

print(data_dir)

print(data_dir.exists())

print(list(data_dir.glob("*")))

/Users/chaehuiju/dev/ai-data-analysis/notebooks
/Users/chaehuiju/dev/ai-data-analysis/data/raw
True
[PosixPath('/Users/chaehuiju/dev/ai-data-analysis/data/raw/customers.csv'), PosixPath('/Users/chaehuiju/dev/ai-data-analysis/data/raw/products.csv'), PosixPath('/Users/chaehuiju/dev/ai-data-analysis/data/raw/orders.csv'), PosixPath('/Users/chaehuiju/dev/ai-data-analysis/data/raw/order_items.csv')]

## 68. KeyError

In [192]:
print(customers.columns.tolist())
print([repr(col) for col in customers.columns])

['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
["'customer_id'", "'name'", "'gender'", "'age'", "'city'", "'signup_date'"]

## 69. 날짜 변환 후 결측치 증가

In [193]:

original_missing = orders["order_date"].isna().sum()
converted = pd.to_datetime(
    orders["order_date"],
    errors="coerce"

)

converted_missing = converted.isna().sum()

print(original_missing, converted_missing)

0 0

70. ID 중복을 잘못 해석함

다음 두 질문을 구분합니다.

 

orders.order_id가 중복되는가?

→ 주문 한 건당 한 행이면 문제 가능성

order_items.order_id가 중복되는가?

→ 한 주문에 여러 상품이 있으므로 정상 가능

 

항상 한 행의 의미와 함께 판단합니다.